### ISSUE TITLE
How to edit environment variables (BuildConfig--> SourceBuildStrategy) ?

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#130]
I need to edit an environment variable in the sourceBuildStrategy.
iClient.update(Resource) is only adding the enviroment variable in the buildconfig. So the buildconfig has 2 variables with the same name.

**Comment by jcantrill** [comment]
@kaimago This ends up being a feature request.  Given the work we have been doing, we have only added functionality as we have needed it.  Setting of env variables should only be done through the public interface once its available.  You are welcome to create a PR or I'll see if I can provide you an accessor

**Comment by kaimago** [comment]
@jcantrill thanks for your help.

Can you share some information about the "public interface". availability / use case ...

**Comment by jcantrill** [comment]
@kaimago Thanks for pointing out that we have not provided a factory method to create buildstrategies for a buildconfig.  I will work on adding that functionality.  In the meantime, you will have to new an instance of the desired class.  IClient has a method to retrieve the associated resource factory from which you can stub a resource buts use only is for top level types like build and deployment configs.
