### ISSUE TITLE
Problems with java client making calls to Origin API

### ISSUE THREAD

**Issue by eivantsov** [openshift/openshift-restclient-java#134]
We, at Codenvy, have build a plugin for OpenShift that works ok against Enterprise 3.1 version.

However, having grabbed the latest Origin version, we have faced a problem. Any calls rest client makes to Origin API get 409 and '{"message":"the body of the request was in an unknown format - accepted media types include: application/json, application/yaml"}' as a response.

After some experiments, it turned out that when a project is created using a web console, content type in the header is set as:

`Content-Type:application/json;charset=UTF-8`

However, when a request is made in Eclipse Che, Content-Type is just application/json. In our code, we can add chaset but it's rest client that makes the final call to Origin API.

I have seen similar problems, for instance http://stackoverflow.com/questions/36009766/openshift-origin-application-with-jboss-developer-studio

**Comment by jcantrill** [comment]
@eivantsov Do you have the latest version of the binaries.  #112 was added a few weeks ago to resolve problems where content-type was not being set.  Additionally, experimenting with both enterprise and origin, the cli does not set encoding and is tolerant of any issues AFAIK tell:

`$ oc create -f service.json --loglevel=8
I0323 07:54:58.046597   16552 debugging.go:99] GET https://localhost:8443/oapi
I0323 07:54:58.047189   16552 debugging.go:106] Request Headers:
I0323 07:54:58.047209   16552 debugging.go:109]     User-Agent: oc/v3.1.0.4 (linux/amd64) openshift/112fcc4
I0323 07:54:58.047224   16552 debugging.go:109]     Authorization: Bearer Yszht1ieTeoDCghEbBgAZntkBOOQG4lh5RabM7o7Kjs
I0323 07:54:58.072665   16552 debugging.go:124] Response Status: 200 OK in 25 milliseconds
I0323 07:54:58.072711   16552 debugging.go:127] Response Headers:
I0323 07:54:58.072722   16552 debugging.go:130]     Cache-Control: no-store
I0323 07:54:58.072733   16552 debugging.go:130]     Content-Type: application/json
I0323 07:54:58.072743   16552 debugging.go:130]     Date: Wed, 23 Mar 2016 11:54:58 GMT
I0323 07:54:58.072752   16552 debugging.go:130]     Content-Length: 32
I0323 07:54:58.072824   16552 request.go:796] Response Body: {
  "versions": [
    "v1"
  ]
}
I0323 07:54:58.073287   16552 decoder.go:141] decoding stream as JSON
I0323 07:54:58.079049   16552 debugging.go:99] GET https://localhost:8443/api
I0323 07:54:58.079074   16552 debugging.go:106] Request Headers:
I0323 07:54:58.079084   16552 debugging.go:109]     User-Agent: oc/v1.1.0 (linux/amd64) kubernetes/4c8e6f4
I0323 07:54:58.079094   16552 debugging.go:109]     Authorization: Bearer Yszht1ieTeoDCghEbBgAZntkBOOQG4lh5RabM7o7Kjs
I0323 07:54:58.081938   16552 debugging.go:124] Response Status: 200 OK in 2 milliseconds
I0323 07:54:58.081990   16552 debugging.go:127] Response Headers:
I0323 07:54:58.082009   16552 debugging.go:130]     Content-Type: application/json
I0323 07:54:58.082025   16552 debugging.go:130]     Date: Wed, 23 Mar 2016 11:54:58 GMT
I0323 07:54:58.082039   16552 debugging.go:130]     Content-Length: 32
I0323 07:54:58.082054   16552 debugging.go:130]     Cache-Control: no-store
I0323 07:54:58.082117   16552 request.go:796] Response Body: {
  "versions": [
    "v1"
  ]
}
I0323 07:54:58.082903   16552 request.go:543] Request Body: {"kind":"Service","apiVersion":"v1","metadata":{"name":"spring-boot","namespace":"bbb","creationTimestamp":null,"annotations":{"openshift.io/generated-by":"jbosstools-openshift"}},"spec":{"ports":[{"name":"8080-tcp","protocol":"TCP","port":8080,"targetPort":8080}],"selector":{"deploymentconfig":"spring-boot-helloworld"},"type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}
I0323 07:54:58.082955   16552 debugging.go:99] POST https://localhost:8443/api/v1/namespaces/bbb/services
I0323 07:54:58.082969   16552 debugging.go:106] Request Headers:
I0323 07:54:58.082996   16552 debugging.go:109]     User-Agent: oc/v1.1.0 (linux/amd64) kubernetes/4c8e6f4
I0323 07:54:58.083007   16552 debugging.go:109]     Authorization: Bearer Yszht1ieTeoDCghEbBgAZntkBOOQG4lh5RabM7o7Kjs
I0323 07:54:58.105048   16552 debugging.go:124] Response Status: 201 Created in 22 milliseconds
I0323 07:54:58.105082   16552 debugging.go:127] Response Headers:
I0323 07:54:58.105105   16552 debugging.go:130]     Cache-Control: no-store
I0323 07:54:58.105116   16552 debugging.go:130]     Content-Type: application/json
I0323 07:54:58.105124   16552 debugging.go:130]     Date: Wed, 23 Mar 2016 11:54:58 GMT
I0323 07:54:58.105149   16552 debugging.go:130]     Content-Length: 600
I0323 07:54:58.105192   16552 request.go:796] Response Body: {"kind":"Service","apiVersion":"v1","metadata":{"name":"spring-boot","namespace":"bbb","selfLink":"/api/v1/namespaces/bbb/services/spring-boot","uid":"10e41a43-f0ee-11e5-af01-5254001dff69","resourceVersion":"67016","creationTimestamp":"2016-03-23T11:54:58Z","annotations":{"openshift.io/generated-by":"jbosstools-openshift"}},"spec":{"ports":[{"name":"8080-tcp","protocol":"TCP","port":8080,"targetPort":8080}],"selector":{"deploymentconfig":"spring-boot-helloworld"},"portalIP":"172.30.129.160","clusterIP":"172.30.129.160","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}
service "spring-boot" created
`

**Comment by eivantsov** [comment]
It looks like this commits isn't in your latest release which is 3.0.1-Final. Any plans to release soon?

**Comment by jcantrill** [comment]
@fbricon @adietish Given that we will be going into codefreeze tomorrow for jbosstools, any ideas around when we will release 4.0.0-FINAL?

**Comment by fbricon** [comment]
Release should happen today or tomorrow at the latest

**Comment by eivantsov** [comment]
@fbricon thanks! Looking forward to it!

**Comment by jcantrill** [comment]
just released.

**Comment by jcantrill** [comment]
@eivantsov have you had an opportunity to verify the new release resolves your issue?

**Comment by jcantrill** [comment]
closing
