### ISSUE TITLE
How to add-role-to-user ?

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#141]
I miss the function to add a role to a serviceaccount.
Something like this:

oc policy add-role-to-user edit system:serviceaccount:projectname:serviceaccount -n ..

Is this a featurerequest or is it already implemented ?

**Comment by jcantrill** [comment]
This would be a feature request to add an API to do this in a simplified fashion.  You can probably, however, recreate all the steps that the oc binary is doing.  By enabling '--loglevel=9' on the 'oc policy' command you can see the REST calls its making.

**Comment by jcantrill** [comment]
Closing issue for now.  Feel free to open a feature request https://issues.jboss.org/browse/OSJC
