### ISSUE TITLE
Authentication rest client  via tokens

### ISSUE THREAD

**Issue by securelord** [openshift/openshift-restclient-java#143]
Using the rest client I was faced with a problem - how to authenticate the client using the tokens?
What actions need to perform on the server?

**Comment by jcantrill** [comment]
Retrieve your token from `SERVER_URL/oauth/token/request` or by `oc whoami --token` and provide it like

`client.setAuthorizationStrategy(new TokenAuthorizationStrategy(token));`

**Comment by jcantrill** [comment]
@securelord closing this issue as it is no longer relevant as of #179.  Supply the token to the ClientBuilder as described in the README.
