### ISSUE TITLE
WatchClient should support proxy

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#171]
WebSocketClient implementation in WatchClient has unfortunately no proxy support.

Is there any chance that you change the WebSocket-implementation or do you wait for Jetty 10 WebSocketClient ?

http://stackoverflow.com/questions/29430503/java-websocket-with-proxy
http://stackoverflow.com/questions/32785018/configuring-jetty-websocket-client-to-use-proxy

**Comment by jcantrill** [comment]
We would probably not change the client library other then upgrade.  Can you provide a test scenario to replicate.
cc @fbricon

**Comment by jcantrill** [comment]
@kaimago I havent fully digested the last link, but it appears there are certain proxies that are supported by websockets and jetty.  I'll need to read further since I dont see an obvious timelien for Jetty 10

**Comment by kaimago** [comment]
I think as far as Jetty WebSocketClient doesn't support to set a proxy there is no chance to get it working. I also didn't find a timeline for Jetty 10, so it's probably take a while.

What do you mean with test scenario to replicate. To reproduce the behaviour you need to put a proxy between your openshift calls.

**Comment by jcantrill** [comment]
@kaimago #179 removed the dependency on jetty to okhttpclient.  Please retest your proxy concerns with this change to see if it addresses them.

**Comment by kaimago** [comment]
It's working :)

Thanks a lot !!!

**Comment by kaimago** [comment]
Are you planning to build a release-version soon ? :)

**Comment by jcantrill** [comment]
I will deploy a snapshot release but it might be awhile before the final
Jar is out

On Monday, July 11, 2016, Kai <notifications@github.com> wrote:

> Are you planning to build a release-version soon ? :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/issues/171#issuecomment-231696345>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEVnOJK4yDDfFBBQibnPQ_ascxrtCgN6ks5qUhiLgaJpZM4IxxZ6>
> .
>


-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by jcantrill** [comment]
deployed the latest snapshot
