### ISSUE TITLE
How to change login timeout?

### ISSUE THREAD

**Issue by dermitdemwolftanzt** [openshift/openshift-restclient-java#172]
Using the AuthorizationClient with BasicAuthorizationStrategy and socket TIMEOUT is hardcoded to 10000(10 secs.). How can I overwrite this value?

**Comment by dermitdemwolftanzt** [comment]
Solution for me: unfortunately the class AuthorizationClient is not intended to be extended. So I have replaced this class with my own Implementation class, it seems not to be the best approach. Any suggestions are more than welcome, thank you!

**Comment by jcantrill** [comment]
@dermitdemwolftanzt There obviously is no solution without changing the code.  I would consider submitting a PR that makes changes to ClientBuilder to pass a default timeout to the IClient impl and subsequently to the auth client.   This would probably be the cleanest solution.  I'll see if I can work something up.

**Comment by dermitdemwolftanzt** [comment]
Unfortunately the **login** timeout issue still existing. For eg. if I'm using the following code to initilise my auth-client:
IAuthorizationClient authClient = new AuthorizationClient(client);
IAuthorizationContext context = authClient.getContext(client.getBaseURL().toString());
client.setAuthorizationStrategy(new TokenAuthorizationStrategy(context.getToken()));
etc. Regarding to this I'll send bugfix's proposal.
To the reading and connecting timeouts, until now I could set the my own timeout using the following codes:
client.getBaseURL().openConnection().setConnectTimeout(new_timeout);
client.getBaseURL().openConnection().setReadTimeout(new_timeout);
They should have the same affects, are't they?

best regards,
Tommy
