### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by MitchTalmadge** [openshift/openshift-restclient-java#184]
Does any documentation exist for this client? It's pretty useless without any documentation showing how to actually use it. The snippet on the README.md has a syntax error and uses a deprecated method.

```java
IClient client = new ClientFactory().create(url, sslCertCallback); // ClientFactory is deprecated.
client.setAuthorizationStrategy(new TokenAuthorizationStrategy("ADSASEAWRA-AFAEWAAA"); // Missing closing parenthese.
List<IProject> projects = client.list(ResourceKind.PROJECTS, "test-project");
```

**Comment by jcantrill** [comment]
There is a pending pull request here
https://github.com/openshift/openshift-restclient-java/pull/179 that will
be merged shortly which more accurately reflects the current state of the
client and includes an updated README. The largest difference is around the
authorization bits. I expect the PR to merge in the next several days.

On Thursday, June 30, 2016, Mitch Talmadge <notifications@github.com> wrote:

> Does any documentation exist for this client? It's pretty useless without
> any documentation showing how to actually use it. The snippet on the
> README.md has a syntax error and uses a deprecated method.
>
> IClient client = new ClientFactory().create(url, sslCertCallback); // ClientFactory is deprecated.
> client.setAuthorizationStrategy(new TokenAuthorizationStrategy("ADSASEAWRA-AFAEWAAA"); // Missing closing parenthese.List<IProject> projects = client.list(ResourceKind.PROJECTS, "test-project");
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/issues/184>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEVnOBqep7wu0EYr9K_HDSYiRjPRyvsUks5qRC5agaJpZM4JCloS>
> .
>


-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by MitchTalmadge** [comment]
Looks great, thanks!
