### ISSUE TITLE
Connection TLS/SSL error - not sending HOST in header?

### ISSUE THREAD

**Issue by MarkRx** [openshift/openshift-restclient-java#189]
Hello,

I am getting a TLS/SSL certificate error when attempting to log in to OpenShift. Basically what is happening is when I hit the openshift url (aaa.myinstance.com:8443) the code ends up with a cert error that requires "openshift-signer@1488501423" instead of being what is expected (the one used by aaa.myinstance.com:8443). That is an internal certificate that I am told is used by a cluster controller. According to an environment engineer this is likely caused by the code not sending the http HOST header. The situation can be replicated below:

Wrong:
$ openssl s_client -connect aaa.myinstance.com:8443 | grep issuer                 
depth=1 CN = openshift-signer@1488501423
verify error:num=19:self signed certificate in certificate chain
issuer=/CN=openshift-signer@1488501423

Right:
$ openssl s_client -connect aaa.myinstance.com:8443 -servername aaa.myinstance.com | grep issuer
depth=1 DC = com, DC = <...>, CN = <...>
verify return:1
depth=0 C = US, ST = <...>, L = <...>, O = "<...>", OU = <...>, CN = *.myinstance.com
verify return:1
issuer=/DC=com/DC=<...>/CN=<...>

Here is what I am doing in code:

```
		IClient client = new ClientFactory().create(oAuthURL.toString(), new DefaultSSLCertificateCallback());

		client.setAuthorizationStrategy(new BasicAuthorizationStrategy(username, password, null));
		IAuthorizationContext ctx = client.getContext(oAuthURL.toString());
		String token = ctx.getToken();
```

```
public class DefaultSSLCertificateCallback implements ISSLCertificateCallback {

	private static final HostnameVerifier hostnameVerifier = new DefaultHostnameVerifier(PublicSuffixMatcherLoader.getDefault());
	
	@Override
	public boolean allowCertificate(X509Certificate[] chain) {
		// From what I found in the source code the default trust manager is hit first to see if the chain is trusted
		// before this is called. If it's not trusted then we shouldn't trust it. If it is we are not called.
		return false;
	}

	//https://hc.apache.org/httpcomponents-client-ga/httpclient/xref/org/apache/http/conn/ssl/SSLConnectionSocketFactory.html
	@Override
	public boolean allowHostname(String hostname, SSLSession session) {
		try {
			if (!hostnameVerifier.verify(hostname, session)) {
				final Certificate[] certs = session.getPeerCertificates();
				final X509Certificate x509 = (X509Certificate) certs[0];
				final X500Principal x500Principal = x509.getSubjectX500Principal();
				throw new SSLPeerUnverifiedException("Host name '" + hostname + "' does not match " +
						"the certificate subject provided by the peer (" + x500Principal.toString() + ")");
			}
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		
		return true;
	}

}
```

**Comment by MarkRx** [comment]
The TLS Client Hello message in java is not sending server_name (SNI). This results in the wrong cert being returned. More research pending...

**Comment by MarkRx** [comment]
I may be hitting this jre bug: https://bugs.openjdk.java.net/browse/JDK-8144566

**Comment by MarkRx** [comment]
It is indeed a jre bug. Workaround for me was to not use a custom ISSLCertificateCallback

**Comment by adietish** [comment]
oh, wow, nice catch! 
...fixed in OpenJDK 9 only afaics.
In JBoss Tools we actually use a custom certificate callback and thus didnt notice :(

**Comment by MarkRx** [comment]
I do not know about other JDKs. I was running the Oracle sun jdk 1.8.0_91. Not using a custom certificate callback works for me.

**Comment by jcantrill** [comment]
@adietish we appear to have a solution here with a limited number of cases (1) that have exposed this issue.  I would agree to not doing anything for now and look into a workaround if we see this is becoming problematic
