### ISSUE TITLE
New app from template

### ISSUE THREAD

**Issue by matteoturra** [openshift/openshift-restclient-java#192]
Hi, I didn't find how to call new-app (or Add to Project in web UI) command via REST API.
Is this feature implemented?

**Comment by jcantrill** [comment]
The new-app functionality is written all client-side in the oc binary and is not necessarily represented in this library. The openshift-restclient-java does provide some similar capabilities as the binary but it mostly is a java representation of the openshift golang types.

Please see https://github.com/openshift/openshift-restclient-java/blob/master/README.md for creating a project and generally for adapting the client to its capabilities to do some other things.  An example of using the capability to process and apply templates is here https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java#L66 .

**Comment by jcantrill** [comment]
Closing.  Please reopen if you require additional info.
