### ISSUE TITLE
ResourceFactory unable to create ConfigMap instances

### ISSUE THREAD

**Issue by lulf** [openshift/openshift-restclient-java#208]
I'm having an issue in my client using a watcher to watch config maps after upgrading to 5.1.0.Final. My watcher listener code looks like the following:

```java
    public void connected(List<IResource> resources) {
        for (IResource resource : resources) {
       
            IConfigMap configMap = (IConfigMap) resource;
        }
    }
```

The cast worked earlier, but failed on 5.1.0.Final. After 4.0.5, the ConfigMap kind was explicitly removed from ResourceFactory (https://github.com/openshift/openshift-restclient-java/commit/557d5ee492ec4d6bafb9d1fa5006afcab8e421b2), and I suppose it was to be created using this new typeMapper. However, after reading the code of the WatcherClient and ResourceFactory, I can't really see that the typemapper is used when receiving the response. The ResourceFactory seems to still use the IMPL_MAP mapping where the configmap kind does not exist.

**Comment by lulf** [comment]
For reference, this is the exception:

2016-09-15 12:24:59 INFO  OpenshiftConfigMapDatabase:60 - Resource kind is ConfigMap with class com.openshift.internal.restclient.model.KubernetesResource
Exception in thread "OkHttp Dispatcher" java.lang.ClassCastException: com.openshift.internal.restclient.model.KubernetesResource cannot be cast to com.openshift.restclient.model.IConfigMap
	at 

The ResourceFactory fallbacks to KubernetesResource if it can't find a type mapping.

**Comment by jcantrill** [comment]
@lulf I wonder if this is a bad merge since I thought the 'typemapper' would not come in until https://github.com/openshift/openshift-restclient-java/pull/205 is merged.  I'll have to investigate
