### ISSUE TITLE
HorizontalPodAutoscaler 

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#212]
Are you planning to support HorizontalPodAutoscaler ?

https://docs.openshift.com/enterprise/3.2/dev_guide/pod_autoscaling.html

**Comment by jcantrill** [comment]
I'm not certain what you mean regarding "..planning to support HorizontalPodAutoscaler..".  Do you mean a  type that represents the same thing?  If so, currently there is no explicit direction to add it to the client unless there is a need for it.  We generally add types and functionality as requested or needed, primarily driven by either Jboss tools or the OpenShift jenkins plugin.

**Comment by kaimago** [comment]
yes, I mean a new type for HorizontalPodAutoscaler.  I just want to ask before I switch to kubernetes-client.
