### ISSUE TITLE
Custom labels not set for pods

### ISSUE THREAD

**Issue by vnugent** [openshift/openshift-restclient-java#219]
When deploying new app with custom labels all labels are created in services, pods, etc as expected.
`oc new-app --template=hawkular-full -l mylabel=foo`

In my case the label 'ircbot' is correctly created in Deployment Config, Services and Routes but missing in the Pod yaml. 

```java
List<IResource> status = targetProject.accept(
 new CapabilityVisitor<IProjectTemplateProcessing, List<IResource>>() {
   @Override
   public List<IResource> visit(IProjectTemplateProcessing capability) {
	ITemplate original = getUniqueGlobalTemplate(templateName);
	original.addObjectLabel("ircbot", templateName);
	ITemplate processed = capability.process(original);
	Collection<IResource> resources = capability.apply(processed);
	return handleResponse(resources);
   }
...
````

**Comment by jcantrill** [comment]
You are seeing a general behavior associated with templates and not necessarily an issue in this client.  'oc new-app' has a lot of functionality built into the client which takes the proactive approach of spinning through all the resources it will create and applying the labels that are passed in.  Templates will apply the defined labels to all the top level object defined in the template, but these will not be applied to any of the resources that are produced (e.g. rc, pods); its just a known limitation with templates at this time.

You can achieve a simliar result by spinning through the processed objects, finding the deploymentconfigs, and updating the labels found on the pod spec.  If that is not achievable, maybe we should expose a setter.

**Comment by vnugent** [comment]
thanks for the explanation
