### ISSUE TITLE
ResouceKind Endpoint is missing

### ISSUE THREAD

**Issue by bjartek** [openshift/openshift-restclient-java#242]
Hello, 

It looks like endpoints from the kubernetes api is missing. https://docs.openshift.com/container-platform/3.3/rest_api/kubernetes_v1.html#v1-endpoints

Is there a reason for this or is it just something that has not been done yet?

**Comment by jcantrill** [comment]
Resource types have only been added as needed, mainly in support of Jboss Tools.  You can still retrieve endpoints by providing it "endpoint" as the resource kind which will return a generic resource instance.  I will take a not to add it in.

**Comment by bjartek** [comment]
Thanks!

**Comment by jcantrill** [comment]
deployed latest snapshot to nexis with this change.
