### ISSUE TITLE
"The api endpoint for kind 'ImageStream' requires a namespace"

### ISSUE THREAD

**Issue by securelord** [openshift/openshift-restclient-java#244]
Hi.
I try get all ImageStream's from server:
`List<IImageStream> streams = *IClient*.list(ResourceKind.IMAGE_STREAM);`

but get exception:

`The api endpoint for kind 'ImageStream' requires a namespace`

**Comment by securelord** [comment]
Earlier I used the version 4.0.5 and all was well.

**Comment by jcantrill** [comment]
You must provide a namespace.  This method signature should be deprecated since it was for the 'default' namespace and only cluster-admins can make queries against it.

**Comment by securelord** [comment]
Hi.
Thanks for answer.
How can I get a list of server templates(php:5.6, ruby:2.0 etc) without reference to the name of the project?

Thanks.
