### ISSUE TITLE
Support for async execution

### ISSUE THREAD

**Issue by bjartek** [openshift/openshift-restclient-java#256]
Have you considered supporting an async execution model for the main operations?

OkHttp supports it really well and looking at the source it should not be that hard to just create another Listener kinda like the WatchListener and expose some new methods that require that listener. 

Then it would be possible to create a separate lib with RxJava that just wraps that listener. Or spring Reactor, or Akka or anything Reactive.

I can give a stab at implementing this in a PR if you are interested in it at all. 

Reason:
At work we use this client pretty heavily. We have this chain of calls that would benefit from beeing executed in an async fashion. 

For each "application" we typically fetch DC, ImageStream, Pods, Latest RC.

**Comment by jcantrill** [comment]
We have not but feel free to offer a PR.  The largest consumer is jbosstools that wraps many operations into a job that allows us to achieve the same effect. I would consider, for sake of making it cleaner, to introduce an asyncclient that is adapted from IClient.  I'm interested in seeing your proposal

**Comment by bjartek** [comment]
Just a heads up that this is out-of-scope for me to do at this moment. There will be no PR from me on this issue. Feel free to close it if you want.
