### ISSUE TITLE
lacking support for BuildConfig source type "Binary"

### ISSUE THREAD

**Issue by adietish** [openshift/openshift-restclient-java#259]
Our build configs are not supporting the source type "Binary" as documented here: https://docs.openshift.com/container-platform/3.3/dev_guide/builds.html#binary-source

**Comment by adietish** [comment]
@jcantrill I discovered this when we were reported https://issues.jboss.org/browse/JBIDE-23815 in JBoss Tools

**Comment by adietish** [comment]
btw. in this we can see the drawback of using enums:
If the source type wasnt an enum we could simply display the value, ommitting the "advanced" properties for it. Given that the source type is an enum in the library, we can only get either return null or an "UNKNOWN" enum. If it was a normal class we could return a generic type which would at least show the name.

**Comment by jcantrill** [comment]
@adietish I thought we removed all references to enums for the reasons you describe.

**Comment by bakito** [comment]
This would be a cool feature, since I'm triggering binary builds from build pipelines.

The work-around, I'm currently using is via the openshift cli.

sh 'oc start-build --from-dir=<dir_name>'

**Comment by vgribok** [comment]
It's disappointing this issue is still open more than a year after being reported. Binary source is a valuable feature.

**Comment by adietish** [comment]
This issue wasn't closed by mistake. This was implemented with https://issues.redhat.com/browse/OSJC-283 and was committed with 1939942e913164e17aa3a29cc333c9b53ee4b8e1.
Closing as resolved.
