### ISSUE TITLE
Jolokia response, error with 5.5.0.FINAL

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#260]
With 5.5.0.FINAL calls against jolokia api are not working anymore, because they don't have a "kind" / "version" in response.

Error is occuring in ResourceFactory (227) --> getResourceClass (IVersionedApiResource endpoint = mapper.getEndpointFor(version, kind);)

With 5.3.0.FINAL it was running properly.

**Comment by jcantrill** [comment]
Can you provide more detail of what you are trying to do?  Maybe include information regarding the resource you are trying to retrieve?  The version of the server you are calling.

**Comment by kaimago** [comment]
like in the URLBuilderTest --> testAddingASubContext

@Test
	public void testAddingASubContext() {
		IResource resource = givenAResource(ResourceKind.POD, KubernetesAPIVersion.v1, "https:demo-app-8-3gehi:8778");
		String url = builder.
				resource(resource)
				.name("bar")
				.subresource("proxy")
				.subContext("jolokia/exec/java.util.logging:type=Logging/getLoggerLevel/abc")
				.build().toString();
		assertEquals(String.format("%s/api/v1/namespaces/https:demo-app-8-3gehi:8778/pods/bar/proxy/jolokia/exec/java.util.logging:type=Logging/getLoggerLevel/abc", BASE_URL),url.toString());
	}
