### ISSUE TITLE
There is no possibility to update application from template

### ISSUE THREAD

**Issue by strowk** [openshift/openshift-restclient-java#261]
In openshift CLI there is possibility to apply changes in template. 
case is:
use template to create application
change template
process and apply updated template 
after this three steps openshift CLI would create missing resources and update existing, but in java client IProjectTemplateProcessing#apply only leads to creation of resources (no update for existing). 
In case if resource already exists - creation for it would fail and we would have false positive apply - like it have been done successfully, but in reality "update" for existing resources would just be ignored.

**Comment by jcantrill** [comment]
There is not guarantee this client functions in the same manor as the CLI.  There is quite a bit of logic that is client side as part of the CLI that has to be reproduced in each client (e.g. managment console, this one).  I recommend you open a feature request to move this logic server side for other clients to consume.

Feel free to open a PR to correct the logic here.  Community additions are always welcome.
