### ISSUE TITLE
IUpdatable capability does not post anything 

### ISSUE THREAD

**Issue by strowk** [openshift/openshift-restclient-java#262]
Code from 
https://github.com/openshift/openshift-restclient-java/blob/master/src/test/java/com/openshift/internal/restclient/capability/resources/UpdateableCapabilityTest.java

`		service.accept(new CapabilityVisitor<IUpdatable, IService>() {

			@Override
			public IService visit(IUpdatable capability) {
				capability.updateFrom(target);
				return null;
			};
		}, null);`

looks like it would really update service in openshift, but in
https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/capability/resources/UpdateableCapability.java
it looks like it just update json and it's all. You have to manually call client to update after this. 
For example ProjectTemplateProcessing capability would really call client.
https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/capability/resources/ProjectTemplateProcessing.java

This behavior is strange and uncommon.

**Comment by jcantrill** [comment]
This test essentially confirms that the service is updated to match the service passed to it.  As you note, this does not actually reconcile the changes to the server.  It may be the interface and class are poorly named.  You would have to additionally pass the 'updated' service to the client for the state to be reconciled.
