### ISSUE TITLE
Clarification: What openshift version can the 5.5.0 client be used with?

### ISSUE THREAD

**Issue by heiko-braun** [openshift/openshift-restclient-java#271]

**Comment by Ladicek** [comment]
The `README` has a nice _Compatibility_ table... except that it doesn't really provide much info. That table should be filled with actual content, at least for each released version IMHO.

**Comment by jcantrill** [comment]
TBH, we have been derelict in keeping the client moving along as we should.  The compatibility table is really a documentation of versions that I have explicitly tested and know to work with given versions of the OS cluster.  You may find it still works with other versions, but I have not had an opportunity to explicitly verify that.

**Comment by jcantrill** [comment]
@adietish Can you attest to what version 5.5 compatible with?  What version of JBT consumes it now?

**Comment by jorgemoralespou** [comment]
Since 5.6.0 is released, maybe you should reflect to which versions do 5.5.0 and 5.6.0 match (or are tested).
