### ISSUE TITLE
Container.setCommandArgs adds arguments instead of replacing them

### ISSUE THREAD

**Issue by dernasherbrezon** [openshift/openshift-restclient-java#273]
In Java "set" verb often refer to "set and replace previous". See `List.set` for example or getters/setters pattern. Currently `container.setCommandArgs` will append arguments to the existing list, rather than replacing original list. 

Expect:
- replace previously defined OR
- rename method to "addCommandArgs" and add new method "putCommandArgs". As changing command line args is a very useful feature.

**Comment by jcantrill** [comment]
@dernasherbrezon Pull requests are welcome.  We will need to alias and deprecate the existing functionality to comply with your suggestion
