### ISSUE TITLE
Please update the pom.xml version if a tag is created

### ISSUE THREAD

**Issue by heiko-braun** [openshift/openshift-restclient-java#274]
The pom.xml of the `5.6.0.Final` tag still carries the `5.6.0-SNAPSHOT` version: https://github.com/openshift/openshift-restclient-java/blob/openshift-restclient-java-5.6.0.Final/pom.xml#L20. The pom.xml version should be `5.6.0.Final` instead.

**Comment by jcantrill** [comment]
@adietish Can you update? Did you publish 'final'?

**Comment by heiko-braun** [comment]
Would also work for me if it's fixed with the next release

**Comment by kenfinnigan** [comment]
I'm not sure how, but though the tag in the repository says SNAPSHOT, the version available in maven central is Final: http://search.maven.org/#artifactdetails%7Ccom.openshift%7Copenshift-restclient-java%7C5.6.0.Final%7Cjar

Would certainly be better if the tag had the actual version name of the release in pom.xml

**Comment by adietish** [comment]
@heiko-braun @jcantrill @kenfinnigan that's how we released in openshift-restclient-java so far: tag the source, change the pom, deploy to nexus and commit the bump to the next snapshot in source. The only minor downside of it I see is that the version in pom/source that the tag is pointing to is wrong, the code is correct though. We can change this for the next release if the consensus is that we should change this approach.

**Comment by heiko-braun** [comment]
@adietish The reason for requesting this change is that the productisation tools cannot build a tag correctly if the version points to a snapshot in `pom.xml`. For a seamless integration we would need to the `pom.xml` to correspond to the tag version.

**Comment by adietish** [comment]
@heiko-braun latest tags match your requirement afaics. Agree to resolve this issue?

**Comment by heiko-braun** [comment]
yes, thanks @adietish

**Comment by adietish** [comment]
@heiko-braun thx for confirming. resolving.
