### ISSUE TITLE
can't get types scoped by an apiGroupName

### ISSUE THREAD

**Issue by jhalliday** [openshift/openshift-restclient-java#285]
$ oc --loglevel=10 get TemplateInstance
...
GET https://192.168.42.1:8443/apis/template.openshift.io/v1/namespaces/myproject/templateinstances
...

client.get("TemplateInstance", "myproject");
com.openshift.restclient.UnsupportedEndpointException: Unable to determine the api endpoint for kind 'TemplateInstance'

The URLBuilder constructs a VersionedApiResource with apiGroupName=null, so it doesn't match the one in ApiTypeMapper.resourceEndpoints, since equals is sensitive to the group name.

**Comment by jcantrill** [comment]
@adietish Care to try to address?

**Comment by dernasherbrezon** [comment]
Due to that StatefulSets are not supported as well.
