### ISSUE TITLE
can't get UID from IUser

### ISSUE THREAD

**Issue by tplevko** [openshift/openshift-restclient-java#286]
Using this short code I can get all the users on my minishift instance:

final List<IResource> resource = client.list("users");
for (IResource r : resource) {
	IUser user = (IUser) r;
	log.info(user.--------);
}

There is however no method "getUid" in IUser, using which I could get the user UID. 
The oc get user command out for ilustration:
NAME           UID                                    FULL NAME   IDENTITIES
aaa            0b234ab8-8ca9-11e7-b4a3-1246c04ae70e               anypassword:aaa
aaaa           d9c2fd7b-8bcb-11e7-b4a3-1246c04ae70e               anypassword:aaaa

**Comment by jcantrill** [comment]
We will add an accessor but as a work around you can use the capability to retrieve the value [1].  I haven't tried the following but it should be something like:
```
id = user.accept(new CapabilityVisitor<IPropertyAccessCapability,String>() {

		@Override
		public String visit(IPropertyAccessCapability cap) {
                    return cap.asString("metadata.uid");
               }
        }, null);
``` 

[1] https://github.com/openshift/openshift-restclient-java#usage
[2] https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/restclient/capability/resources/IPropertyAccessCapability.java
[3] https://github.com/openshift/openshift-restclient-java/blob/master/src/test/java/com/openshift/internal/restclient/capability/resources/PropertyAccessCapabilityTest.java

**Comment by tplevko** [comment]
Thank you Jeff, it works just fine!

**Comment by adietish** [comment]
stumbled upon this simple request and thought I'd give it a try: https://github.com/openshift/openshift-restclient-java/pull/320

**Comment by adietish** [comment]
@tplevko dare to give it a quick review?

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
resolving since PR was merged.
