### ISSUE TITLE
How to set env variable in buildConfig

### ISSUE THREAD

**Issue by nemoo** [openshift/openshift-restclient-java#292]
Hi!

Sorry, this is really a usage question, if wanted I can also repost it to stackoverflow.

I need to update an env entry in an existing buildConfiguration. In Pseudocode I would need something like:

Patch buildconfig "myexistingbuildconfig":
set "spec" > "strategy" > "sourceStrategy" > "env" > "name": "ARTEFACT_URL"
to "value": "https://www.artefactserver.com/example/1" 

I looked into the tests but I couldn't find the information on how to go about creating the patch for the build config as described above and then submitting it.

I started naively with:
    val resource: IResource = client.getResourceFactory.stub(ResourceKind.BUILD_CONFIG, "mybuildConfig")
    client.update(resource)

How should I proceed?

**Comment by jeffmaury** [comment]
You should use com.openshift.restclient.model.build.IBuildConfigBuilder then call usingSourceStrategy to get com.openshift.restclient.model.build.IBuildConfigBuilder.ISourceStrategyBuilder where you have a withEnvVars method.

Please note this is not the place to ask for questions, there is a mailiing list for that

**Comment by nemoo** [comment]
Thanks will try that!
