### ISSUE TITLE
Creation ConfigMap

### ISSUE THREAD

**Issue by neon-paradise** [openshift/openshift-restclient-java#293]
Hello

How can I create ConfigMap with data field?
IConfigMap does not allow set it value.
`configMap.getData().put(key, value);` - does not worked

And how add this ConfigMap to DeploymentConfig? 
I did't find the right way.

Help me, please.

**Comment by jeffmaury** [comment]
Please use the Google groups for questions. There are two issues there:
- IConfigMap is read only, changed to the returned map are not propagated
- in IContainer, there is no provision for ConFigMap based variables

Feel free to open tickets

**Comment by neon-paradise** [comment]
I'm so sorry, but I could not find the Google group.
Could you send me a link?

**Comment by jeffmaury** [comment]
Sorry I was wrong this is a ML. See https://github.com/openshift/openshift-restclient-java

**Comment by jcantrill** [comment]
@neon-paradise Pull requests are welcome.  There are several examples in the library for model changes
