### ISSUE TITLE
Ignoring SSL issues

### ISSUE THREAD

**Issue by radarsh** [openshift/openshift-restclient-java#301]
Is there an example that shows how to ignore SSL issues, mainly to do with self-signed certificates. I couldn't find a way to provide a custom `X509TrustManager` using the `ClientBuilder`.

**Comment by jeffmaury** [comment]
Issues is not a place to ask questions. Please refer to the mailing list.

**Comment by adietish** [comment]
@radarsh please post a question to https://www.redhat.com/mailman/listinfo/dev or talk to us on IRC on #openshift-client

**Comment by jcantrill** [comment]
@radarsh Are you unable to use the default Noop or provide your own implementation as defined here: https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/restclient/ClientBuilder.java#L85

**Comment by radarsh** [comment]
@jcantrill Since the `sslCertificateCallback` is already initialised to `NoopSSLCertificateCallback`, I don't have to. But even if I explicitly set it to `NoopSSLCertificateCallback` or my own implementation, the callback never gets fired. I believe this is because the trust manager isn't configurable.

In other libraries, we can usually provide our own dummy implementation of `X509TrustManager` which ignores SSL issues. However, [here](https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/restclient/ClientBuilder.java#L200) it doesn't seem to be the case as it is hardwired within the `ClientBuilder`.

Apologies I understand I am not supposed to be asking questions here but I'm just replying to a question directed to me.
