### ISSUE TITLE
[feature request] support liveness probe(s)

### ISSUE THREAD

**Issue by adietish** [openshift/openshift-restclient-java#302]
It turns out that for https://issues.jboss.org/browse/JBIDE-24868 we'd need to access/alter liveness probe properties.
If you have a liveness probe defined (like many templates these days: nodejs, eap, etc.) your pod gets killed and restarted by the rc if the pod wont succeed with the liveness probe. 
In https://issues.jboss.org/browse/JBIDE-24868 we face the situation where you'd break your code at a breakpoint. If you keep it halted for more than the lifeness probed defined timeout, your pod gets killed & your debug session in Eclipse gets terminated.
To avoid that we need to alter/disable an existing liveness probe when debugging.
@jcantrill Agree? Thoughts?

**Comment by adietish** [comment]
@jcantrill turns out that for https://issues.jboss.org/browse/JBIDE-24868 we'd need to access/alter liveness probe properties.
If you have a liveness probe defined (like many templates these days: nodejs, eap, etc.) your pod gets killed and restarted by the rc if the pod wont succeed with the liveness probe. 
In https://issues.jboss.org/browse/JBIDE-24868 we face the situation where you'd break your code at a breakpoint. If you keep it halted for more than the lifeness probed defined timeout, your pod gets killed & your debug session in Eclipse gets terminated.
To avoid that we need to alter/disable an existing liveness probe when debugging.
Agree? Thoughts?

**Comment by jcantrill** [comment]
I agree with your statement; you need to disable the probe but I do not, without looking at the api, believe there is a quick way to accomplish this.  I think your only options are to:

* extend the timeout
* remove the block

**Comment by adietish** [comment]
@jcantrill thanks for the feedback. 
+1, exactly what I had in mind. Mangle initial delay being my favourite for now but I guess other settings would work too.

**Comment by adietish** [comment]
PR (work in progress): https://github.com/openshift/openshift-restclient-java/pull/303

**Comment by adietish** [comment]
merged rudimentary support for readiness- and liveness-probes (for pod containers) at https://github.com/openshift/openshift-restclient-java/pull/303
