### ISSUE TITLE
Add "Namespace" as a ResourceKind and create INamespace interface

### ISSUE THREAD

**Issue by Obirah** [openshift/openshift-restclient-java#314]
Hi,

I'm using the openshift-restclient in an application that needs to update labels on Namespaces/Projects. 
OpenShift only allows to change the labels on resources of the type "Namespace" - when you try to update them on a resource of the type "Project" you'll receive a 422 HTTP error code with a message stating that the field is immutable.

Therefore, it would be nice to have a "ResourceKind.NAMESPACE" constant and an "INamespace" interface in order to deal with this resource type directly.

My workaround for now is to use the "IResource" interface in all calls with generics (create, update, delete in my case) and to define an own constant for the "Namespace" type so that I can use it in "client.getResourceFactory.stub(RESOURCE_KIND_NAMESPACE, name)".

**Comment by adietish** [comment]
+1 since once can see both type is oc cmd-line, too:
```
    * all
    ...
    * namespaces (aka 'ns')
    ...
    * projects
```

**Comment by Obirah** [comment]
@adietish sure, I can do so. Just let me know how to contribute (feature branch, fork, whatever) and what you'll need me to implement in order to create the Namespace type as a counterpart to Project.

**Comment by adietish** [comment]
@Obirah sounds great! To contribute, please create a fork and file a pull request, both on github. 
Let me see where to start with the code and give you some pointers.

**Comment by adietish** [comment]
@jcantrill can you please also chime in for hints and pointers for @Obirah?

**Comment by adietish** [comment]
@Obirah 
The 1st step and most simple step is to create a Namespace class (that extends KuberneteResource) that implements a INamespace interface, like you can see IProject/Project currently does.
Then I'd create accessors for the data that you want to retrieve and manipulate. The json that you get when retrieving a namespace via the oc cmd-line shows you what's available
```
$ oc get namespace test -o=json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "openshift.io/description": "",
            "openshift.io/display-name": "",
            "openshift.io/requester": "admin",
            "openshift.io/sa.scc.mcs": "s0:c8,c2",
            "openshift.io/sa.scc.supplemental-groups": "1000060000/10000",
            "openshift.io/sa.scc.uid-range": "1000060000/10000"
        },
        "creationTimestamp": "2018-03-09T21:19:53Z",
        "name": "test",
        "resourceVersion": "292005",
        "selfLink": "/api/v1/namespaces/test",
        "uid": "9bf521ab-23df-11e8-ba22-e2a386cca5ea"
    },
    "spec": {
        "finalizers": [
            "openshift.io/origin",
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
}
```

**Comment by Obirah** [comment]
Hi @adietish,

thank you for your instructions. I just implemented all the basic stuff and opened up a pull request: https://github.com/openshift/openshift-restclient-java/pull/322

Can you please let me know if that's alright or if anything's missing?

I decided to add the "requester" field to the Namespace implementation as well, because it is a useful information for applications like OpenShift-Self-Services.

**Comment by adietish** [comment]
@Obirah nice! thanks!

**Comment by adietish** [comment]
#322 was merged into master, maven artifact was deployed to repository.jboss.org. Resolving.
@Obirah thanks a lot!

**Comment by Obirah** [comment]
You're welcome! This was my first open-source contribution ever, I hope there's more to come! Thanks for letting me contribute.
