### ISSUE TITLE
MemoryUnit missing

### ISSUE THREAD

**Issue by srueg** [openshift/openshift-restclient-java#324]
Only memory units with the `i` suffix are supported. OpenShift though also supports them without suffix i.e. `G` instead of `Gi`.

**Comment by jcantrill** [comment]
Pull requests are welcome

**Comment by adietish** [comment]
@srueg good observation! Due to serioiusly limited resources it's pretty hard for us to work on this enhancement. We'd therefore love to contributions. Would you be willing to if we assist you?

**Comment by srueg** [comment]
Yeah, I'll see if I can make time for it. The hardest part would probably be the conversion in [PersistentVolume.java:222](https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/model/volume/PersistentVolume.java#L222)?

**Comment by adietish** [comment]
@srueg finally found some time to look at your suggestion and yes I'd agree with your analysis. Maybe @josefkarasek can comment on this since he wrote this.

**Comment by tobru** [comment]
Is there any update on this issue? If there is no progress, we try to find time to come up with a PR.
