### ISSUE TITLE
Remove DeploymentConfig

### ISSUE THREAD

**Issue by neon-paradise** [openshift/openshift-restclient-java#338]
Hello
When I used the OpenShift version 3.6, I deleted the DeploymentConfig and this resulted in the sequential deletion of the DeploymentConfig, the ReplicationController and the all its pods.
When I switched to OpenShift version 3.7,  I delete the DeploymentConfig and this result to deletion of only DeploymentConfig itself. 
Tell me, please, how to remove all 3 entities in the version 3.7 of OpenShift.
Thank you

**Comment by jcantrill** [comment]
@deads2k This is based on somepolicy associated with the DC is it not?

**Comment by deads2k** [comment]
Precisely which API?  `/oapi/v1` or `/apis/apps.openshift.io/v1`.  I think in 3.6 we enabled GC by default, but *only* for `/apis/apps.openshift.io/v1`.  If you were previously sending a GC directive and accidentally forgot it when you moved forward or if you accidentally switched the API you were using, you could get this result.

**Comment by neon-paradise** [comment]
I'm using openshift-restclient-java library version 5.9.1. 
I saw that in version 3.7 there were new api.
How do I understand which of the two api is used in the library? In the code I found only /oapi/v1.
How can I switch to using /apis/apps.openshift.io/v1?
Thank you

**Comment by neon-paradise** [comment]
I need to use the latest version Openshift or openshift-restclient-java library?

**Comment by jeffmaury** [comment]
The latest version of the library

**Comment by adietish** [comment]
@neon-paradise was your issue resolved by using the latest client library? Can we close this issue?

**Comment by adietish** [comment]
api-groups are supported since a few release. Closing.
