### ISSUE TITLE
Can't edit namespace annotation of project

### ISSUE THREAD

**Issue by laszlokiraly** [openshift/openshift-restclient-java#341]
The Editing namespace with oc client:
```
oc edit namespace myproject --loglevel=9
```
results in following request:
```
Request Body: {"metadata":{"annotations":{"openshift.io/somekey":"somevalue"},"namespace":""}}

curl -k -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: oc.exe/v1.7.6+a08f5eeb62 (windows/amd64) kubernetes/c84beff" -H "Authorization: Bearer..." -H "Accept: application/json" https://console.tools.adp.allianz:443/api/v1/namespaces/myproject
```

The only way i found to mimic the oc client patch call looks like this:
```
openshiftClient.execute(new ITypeFactory() {
	
	@Override
	public Object stubKind(String kind, Optional<String> name, Optional<String> namespace) {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public Object createInstanceFrom(String response) {
		// TODO Auto-generated method stub
		return null;
	}
}, HttpMethod.PATCH.toString(), ResourceKind.NAMESPACE, null, "myproject", null, null, new JSONSerializeable() {
	
	@Override
	public String toJson() {
		return "{\"metadata\":{\"annotations\":{\"openshift.io/somekey\":\"somevalue\"}}}";
	}
}, null);
```

Sadly this fails with `Response{protocol=http/1.1, code=415, message=Unsupported Media Type, url=...}` because the content type header is set wrong by the java restclient: `Content-Type: application/json; charset=utf-8`

So basically the solution for this problem could be to add a PATCH case to `com.openshift.internal.restclient.DefaultClient.getPayload(String, JSONSerializeable)`:
```
case "PATCH":
            String json = payload == null ? "" : payload.toJson(true);
            LOGGER.debug("About to send payload: {}", json);
            return RequestBody.create(MediaType.parse("application/strategic-merge-patch+json"), json);
```

Another possible way could be to build the whole request with `com.openshift.internal.restclient.DefaultClient.newRequestBuilderTo(String, String)`, but i have not tried that yet, and also it is an internal API, so i would prefer a working PATCH case.

Do you want me to create a pull request?

**Comment by jcantrill** [comment]
Why not overwrite the namespace annotation of a Project directly using [1] and post it back to the server.  You have access to the full json blob so there is nothing preventing you from an update unless there is some validation by the server that stops you.  This client is not meant to be a full replacement to the offerings of the oc binary
 
[1] https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/restclient/model/IResource.java#L93

**Comment by jcantrill** [comment]
@laszlokiraly This client is capable of using kinds for which there is no concreate model via one of the base implementations of IResource. Projects are a special beast in that they allow for limited changes but you might working with a `namespace` directly; they are more lax.  Consider either using a raw resource from one of the base implementations of IResource or creating a PR to impl the namespace kind

**Comment by laszlokiraly** [comment]
@jcantrill i tried updating `namespace` as a resource and that also failed. That was also the reason why i looked into oc-cli-client.
So i reckon, there is no way to update the annnotation of a namespace of a project with the openshift-restclient-java as of now.

Regarding namespace kind:
I have no idea what you mean with implementing the namespace kind.
I will need specific instructions for implementing the namespace kind.
How much effort will it take?

Compared with my proposed solution. It is imho minimal invasive and provides a way to edit the annnotation of a namespace of a project. So, what is wrong with my solution given problem?

**Comment by jcantrill** [comment]
@laszlokiraly  ref https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/api/models/Endpoints.java

which is 

`curl -k https://localhost:8443/api/v1`

or 
`oc explain namespace`

I expect it will more or less be a copy of project

**Comment by laszlokiraly** [comment]
My Openshift Instance does not allow update whole Namespace but only allows me to patch the Namespace, so I came up with following workaround:
```
Unirest.patch(openshiftHost+ "/api/v1/namespaces/" + name)
	.header("Content-Type", "application/strategic-merge-patch+json")
	.header("Authorization", "Bearer " + token)
	.body(body)
	.asJson();
```

**Comment by adietish** [comment]
@laszlokiraly sorry for the long delay. Oh yes, nice catch! If you're still able to PR this, we'd be more than happy.
