### ISSUE TITLE
still depends on okhttp-ws

### ISSUE THREAD

**Issue by Ladicek** [openshift/openshift-restclient-java#348]
The WebSocket support in this library relies on `okhttp-ws`. That API was unstable and has since disappeared. Since version 3.5, OkHttp no longer ships the `okhttp-ws` artifact. They merged the WebSocket support into the main `okhttp` artifact and stabilized the API. That stabilization, however, is incompatible. See https://medium.com/square-corner-blog/web-sockets-now-shipping-in-okhttp-3-5-463a9eec82d1 and https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-350 for more details.

This prevents us (Thorntail) from upgrading to newer OkHttp versions. See also https://issues.jboss.org/browse/THORN-2165.

**Comment by Ladicek** [comment]
No objections from me :-)

**Comment by adietish** [comment]
@Ladicek we published a new version 7.0.0-SNAPSHOT that's using okhttp 3.11 here: https://repository.jboss.org/nexus/service/local/repositories/snapshots/content/com/openshift/openshift-restclient-java/7.0.0-SNAPSHOT/openshift-restclient-java-7.0.0-20181003.123213-1.jar

Feel free to test it if it works for you. We'd appreciate feedback :)

**Comment by Ladicek** [comment]
I'm currently swamped with other Thorntail work, but I'll try to get to this in a week or two. Thank you very much, though!

**Comment by adietish** [comment]
closing this issue, this was implemented for 7.0.0-SNAPSHOT. We're using in JBoss Tools.
Feel free to open an new issue if things don't work for you as expected.
