### ISSUE TITLE
Question about processing and applying template

### ISSUE THREAD

**Issue by aouertani** [openshift/openshift-restclient-java#353]
Hi all, 

We're writing a tool to interact with our Openshift platform in order to create:
- buildConfig
- creating objects  using template
- updating objects
- ....

One of the needs is to implement the following scenario:

1. oc process -f template.json | oc apply -f  (create objects)
2. oc process -f template.json | oc apply -f - (update the same objects after changing the template)

The oc process/apply existing in the library does only create the object and not updating them. 
I found in the rest docs that the patch could update the object.

Could we used it to do so? Knowing that I checked the implementation of the oc apply and it's more complex than a simple rest call to patch?

Thank you in advance.

Cheers,
Ahmed.

**Comment by jcantrill** [comment]
This library is not intended as a straight port of the oc binary.  It primarily is used to support eclipse Openshift integration.  If you wish to submit a pull requests, they are always welcome

**Comment by aouertani** [comment]
Thanks Jeff for your answer.

But I'm still looking for an answer to the second part of my question. Which is the patch rest call: 
```
$ curl -k \
    -X PATCH \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json-patch+json' \
    https://$ENDPOINT/api/v1/namespaces/$NAMESPACE/services/$NAME <<'EOF'
{
  ...
}
EOF
```

Is this secure way to update the existing objects via the rest (to replace the oc apply)?

Cheers,
Ahmed.

**Comment by jcantrill** [comment]
> Is this secure way to update the existing objects via the rest API (to replace the oc apply)?

I'm not sure I follow your question.  When you say REST do you actually mean the REST api or this library?  It looks as though you have already identified how to properly patch using the REST api.  By 'secure' do you mean ensuring you don't clobber an existing attribute, or reconciling your desired changes with the latest?
