### ISSUE TITLE
List running jobs not working (ResourceKind.JOB missing)

### ISSUE THREAD

**Issue by stoney95** [openshift/openshift-restclient-java#354]
Hi,

I'm trying to delete deployed resources. Therefore i want to list all resources that have a label `deploymentUID` with the same value e.g. `1`. This `list`-method asks me to define a `ResourceKind`(e.g. `BUILD_CONFIG`).  My problem is that there is also a job running that i want to delete, but there is no ResourceKind JOB defined so it's not possible to list the job. 

Maybe I've overseen something but I think it's not defined so far. I also tried to use the `list("job", ..., ...)` but this runs into an error: `c.o.internal.restclient.URLBuilder - There kind 'Job' is not recognized by this client; this operation may fail.`

Is there a possibility to list running jobs? Or (would be even better) can you list all resources (not depending on ResourceKind) with specific label / label-value?

I'm using version 6.1.1 

Regards

**Comment by adietish** [comment]
@stoney95 you're right, unfortunately there are quite some resources that we dont support (yet). We're very limited in terms of coding power. Is there any chance that you'd contribute this with some help?
