### ISSUE TITLE
IPersistentVolume#getProject throws exception

### ISSUE THREAD

**Issue by tonyherstell** [openshift/openshift-restclient-java#378]
`List<IPersistentVolume> persistentVolumes = client.list(ResourceKind.PERSISTENT_VOLUME);
                     for (IPersistentVolume eachPersistentVolume : persistentVolumes) {
                           logger.info("++++++++++++++ Persistance Units ++++++++++++++");
                           logger.info("Name" + eachPersistentVolume.getName());
                           logger.info("Kind" + eachPersistentVolume.getKind());
                           logger.info("Namespace Name" + eachPersistentVolume.getNamespaceName());
                           logger.info("Capacity Unit" + eachPersistentVolume.getCapacityUnit());
                           logger.info("Capcity in Gi" + eachPersistentVolume.getCapacity(MemoryUnit.Gi));
                           logger.info("Capcity" + eachPersistentVolume.getCapacity());
                           Map<String, String> persistanceUnitLabels = eachPersistentVolume.getLabels();
                           for (Map.Entry<String, String> eachLabel : persistanceUnitLabels.entrySet()) {
                                  logger.info("Label        : " + eachLabel.getKey() + " - " + eachLabel.getValue());
                           }
 
                           //eachPersistentVolume.getProject()
 
                           // TODO
                           IPersistentVolumeProperties persistentVolumeProperties = eachPersistentVolume.getPersistentVolumeProperties();                           
 
                     } 
`
eachPersistentVolume.getProject() is allowed through the API but just results in an exception (as it probably should)

**Comment by adietish** [comment]
@jcantrill dare to comment, please?

**Comment by jcantrill** [comment]
@tonyherstell Can you paste a stack trace of the issue?  I presume it's because a PV is a cluster resource and not namespaced.  @adietish maybe we should consider deprecating `getProject()` since it was a convenience method anyway and force use of namespace/project as a string.  If you want a project then maybe you just need to load it explicitly.

**Comment by adietish** [comment]
@jcantrill thx for chiming in. And yes, I agree on deprecating to have a more consistent API.
