### ISSUE TITLE
okHttp is complaining about leaking connections, response was not closed

### ISSUE THREAD

**Issue by adietish** [openshift/openshift-restclient-java#394]
in user programs that use the openshift-restclient-java one can see the following log entries:
```
16:11:43,536 WARNING [okhttp3.OkHttpClient] (OkHttp ConnectionPool) A connection to https://xxxx.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

**Comment by adietish** [comment]
the same problem was spotted and fixed for m2e/aether-connector: https://github.com/takari/aether-connector-okhttp/pull/12

**Comment by jeffmaury** [comment]
@adietish do you know how to reproduce it in JBossTools ?

**Comment by adietish** [comment]
@jeffmaury I create an eap app on employee.openshift.com, have the source imported and the server adapter created. Then I hit "Publish" in the server ctx menu and wait for it to be finished. At some point the following shows up in the Eclipse log:
```
Sep 04, 2019 3:32:44 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://console.rh-us-east-1.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Sep 04, 2019 3:32:44 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://console.rh-us-east-1.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

**Comment by jeffmaury** [comment]
Yes found a way to reproduce. Then switch to the new lib but this is still hapenning

**Comment by adietish** [comment]
@jeffmaury ok, looking into it. What is the case where you can reproduce it?

**Comment by jeffmaury** [comment]
Connect to CDK, list projects, try to connect to 2 other unavailable clusters and wait

**Comment by adietish** [comment]
@jeffmaury this also contains a bump to httpok 4.1.1 - there's no point in upgrading to the latest in the 3.x stream aka 3.12.4 since this one also requires kotlin-stdlib. 
Please test again.

**Comment by adietish** [comment]
@jeffmaury did you find the time to review this?
