### ISSUE TITLE
NO RSH Connectivity API present

### ISSUE THREAD

**Issue by Ask149** [openshift/openshift-restclient-java#416]
Hi, I am trying to access pod information, but I cannot find any API, that does exact work as OpenShift 'oc rsh' command in Java Client.

**Comment by adietish** [comment]
Hi @Ask149 
Indeed, we're missing this. It shouldn't be too difficult to provide this though by delegating this task to the oc binary. We have a class AbstractOpenShiftBinaryCapability that interfaces interaction with the oc command line binary. Currently there are implementations for "oc logs" in OpenShiftBinaryPodLogRetrieval, "oc port-forward" in OpenShiftBinaryPortForwarding and "oc rsync" in OpenShiftBinaryRSync. If you're willing to give this a try we'd love to assist you in this.
