### ISSUE TITLE
How delete all resources by label

### ISSUE THREAD

**Issue by jacksoncastro** [openshift/openshift-restclient-java#420]
The `oc delete all -l <label>` operation deletes all objects matching the specified `<label>`, including the replication controller so that pods are not re-created, as described in the openshift [documentation](https://docs.openshift.com/container-platform/3.11/cli_reference/basic_cli_operations.html#delete).

How can I simulate this operation in the plugin?

E.g:

`$ oc delete all -l app=test`

**Comment by mhagnumdw** [comment]
Hi!
Can anyone help here? :eye: 
Tks!

**Comment by adietish** [comment]
@jacksoncastro @mhagnumdw there's currently no direct support in the delete operation unfortunately. But you could list resources by labels
DefaultClient:
```
    @Override
    public <T extends IResource> List<T> list(String kind, Map<String, String> labels) {
        return list(kind, "", labels);
    }
```
and then iterate over the list and delete the items:
```
    @Override
    public <T extends IResource> void delete(T resource) {
        delete(resource.getKind(), resource.getNamespaceName(), resource.getName());
    }
```
Didn't try it but I'd expect this to work.
