### ISSUE TITLE
Missing ResourceKinds: SubjectAccessReview & SubjectAccessReviewResponse

### ISSUE THREAD

**Issue by Obirah** [openshift/openshift-restclient-java#426]
Currently the client is lacking the ResourceKinds "SubjectAccessReview" and "SubjectAccessReviewResponse". I would like to change that.

I will implement it, once my company has approved the contribution.

**Comment by adietish** [comment]
Hi @Obirah 
great news, very glad to heard this! feel free to ask for our support or to review what you provide. In a sidenote, there was a major overhaul of the resource factory that a user provided: https://github.com/openshift/openshift-restclient-java/pull/335. Unfortunately we never had the time/resources to fully review and integrate this. Maybe it's worth a look or two for your task?

**Comment by Obirah** [comment]
Hi! The resource factory is also coming from my company. The guy who implemented it, was a colleague in my team but is in another team right now.

I would love to have the resource factory, right now we are using our own fork of the client that contains the factory.

What exactly would be the steps to do in order to integrate the factory? In #335 there was a discussion about naming of classes that has never really been resolved and after that the issue died more or less.

**Comment by adietish** [comment]
@Obirah oh, ok, great if you're even willing to provide this into master. I believe that the suggested change would be a great addition to this client. As far as I can see we had a consensus on most complaints after all. I dont have strong opinions on naming and there isnt right or wrong. I'd suggest that we have the PR rebased and ideally well covered by unit tests. Works for you?

**Comment by adietish** [comment]
@Obirah on a more conceptual level I have to point out that our resources in this client are very limited. The replacement being the https://github.com/fabric8io/kubernetes-client. This latter one unfortunately isn't API compatible. Is a switch at some point in the future possible for you guys?
