### ISSUE TITLE
Create custom resource

### ISSUE THREAD

**Issue by gaurav-dhoot** [openshift/openshift-restclient-java#440]
I have some custom resource to setup in the cluster. I have gone through the code and it looks like there isn't a possibility to create these resources as of yet. I may have overlooked the code and would appreciate any help in respect to this.

**Comment by adietish** [comment]
Hi @gaurav-dhoot 

you're unfortunately right. We currently dont support custom resources in this library. Unfortunately our resources in this project are very limited and we're not able to bring new features to this library beside doing the maintenance that we need for the Eclipse tooling that's using this library in.
We would love your contributions though and can also assist you in this quest. There is an unfinished but fairly advanced PR that was getting to what you're missing I think: https://github.com/openshift/openshift-restclient-java/pull/335

Alternatively https://github.com/fabric8io/kubernetes-client/ is the more advanced library within RedHat that supports what you're looking for. 

Cheers
André
