### ISSUE TITLE
Get ServiceAccount Token ala oc sa get-token

### ISSUE THREAD

**Issue by ridvan70** [openshift/openshift-restclient-java#441]
Hi,

How can a service account token be retrieved by the rest-client?

The tokens retrieved by `oc `and the `rest-client` are different. I've analyzed the `oc sa get-token ... --loglevel=10` and did the same calls (get ServiceAccount, get Secret) to OCP with `rest-client` but the token which is returned by `oc` can not be seen in the response payload of the rest-client call for the `SECRET`.

Is there an additional step to obtain the service account token, after retrieving the SECRET of the service account?

Regards,
Ridvan

**Comment by adietish** [comment]
Hi @ridvan70 

I'm unfortunately completely unaware of this. @jeffmaury, @jcantrill Do you have any idea about this?
Alternatively I'd ask in the openshift dev forums/chats about the mechanics required to achieve what you're looking for. Once we know what's needed we could go ahead and implement this in the library.
Can you please point me to the places in oc that you looked into and what request you have sent over the wire?

Cheers
André

**Comment by jeffmaury** [comment]
Yes from the secret that is retrieved, the `token` field is used and base64 decoded
