### ISSUE TITLE
missing tag for 9.0.0.Final

### ISSUE THREAD

**Issue by Ladicek** [openshift/openshift-restclient-java#448]
Hi, just an FYI, I see the 9.0.0.Final version has been released, but this repository doesn't have a tag for it. I think the current `master` branch points to the 9.0.0.Final commit, but having a tag would be nice. Thanks :-)

**Comment by adietish** [comment]
Hi @Ladicek 
thanks for pointing out, pushing those somehow went forgotten. Fixing it.

**Comment by adietish** [comment]
tag added and master bumped to 9.0.1-SNAPSHOT. Closing.
