### ISSUE TITLE
log: Can't access legacy endpoint oapi

### ISSUE THREAD

**Issue by mhagnumdw** [openshift/openshift-restclient-java#462]
Hi !

I get this log in my application on the first OpenShift request: `2020-08-03 18:20:25.428 ERROR com.openshift.internal.restclient.ApiTypeMapper:251 (qtp1327536153-58) - Can't access legacy endpoint oapi`

It appears here https://github.com/openshift/openshift-restclient-java/blob/6e4454dc50640a656ebed46bd85579b59ab4ddce/src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java#L251

Should it really be the `ERROR` level?

**Comment by adietish** [comment]
Hi @mhagnumdw

Good point. It's actually an error but not fatal as long as the newer api endpoints can be reached. I changed this to info in #465. Can you please review it?
