### ISSUE TITLE
OCP 4.7.13 support?

### ISSUE THREAD

**Issue by felipecruz91** [openshift/openshift-restclient-java#468]
Hi,

I am aware that the project is in maintenance mode but I'd like to ask if the latest version (9.0.0-final) currently supports OpenShift 4.7.13 API endpoints?

I'm a bit confused given that the only references to OCP4 apply to ClusterRoleBindings in this file: https://github.com/openshift/openshift-restclient-java/blob/22ce4644a4b257e8b8be9914cb70b575e78f50bb/src/test/java/com/openshift/internal/restclient/model/authorization/RoleBindingTest.java#L31

**Comment by jeffmaury** [comment]
It's being used by JBoss Tools / CodeReady Studio and I'm not aware of any issues.
