### ISSUE TITLE
Remove labels from a resource

### ISSUE THREAD

**Issue by Jelledb** [openshift/openshift-restclient-java#473]
Hey,

With the current API models it does not seem that I am able to remove any labels from (in my case) a namespace. I can only view my labels and add any labels.

I also tried removing certain keys from the `labels` map, but it is a non-mutable map so the actual values are not removed.

(Kotlin code)
```
val namespace = project.namespace
keysToRemove.forEach { namespace.labels.remove(it) }
```

Would be great if this lib could support this operation.

**Comment by Jelledb** [comment]
I see you're not developing this library anymore. I'll have a look at the fabric8 one.

**Comment by adietish** [comment]
@Jelledb Hi Jelle, 
I'm afraid but yes, we're not developing it any more. We started using https://github.com/fabric8io/kubernetes-client in our new projects. Fabric8 kubernetes-client works well and is very feature complete. So it didn't make sense for us to develop this client any further.
