### ISSUE TITLE
Question about Token

### ISSUE THREAD

**Issue by roldancer** [openshift/openshift-restclient-java#73]
Hi,
   I'm trying to use this REST client for OpenShift 3.X, but I have a question about how to get the Token, for instance if I use TokenAuthorizationStrategy, I have to get the token before, could you please tell me what java class and method I should use to get that Token.

client.setAuthorizationStrategy(new TokenAuthorizationStrategy("ADSASEAWRA-AFAEWAAA");

Many thanks.

**Comment by dsimansk** [comment]
You're looking for [this class] (https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/restclient/authorization/AuthorizationClientFactory.java). There might be useful code snippets in unit tests also.

Should work like this and return token for the client. 
```
new AuthorizationClientFactory().create(client).getContext("namespaceName").getToken();
```

**Comment by roldancer** [comment]
Many thanks for your help, it works....

**Comment by dsimansk** [comment]
NP, happy to help.

**Comment by jcantrill** [comment]
Props to @dsimansk for answering.
