### ISSUE TITLE
Create a project using templates.

### ISSUE THREAD

**Issue by fernanzambrano** [openshift/openshift-restclient-java#76]
Hi, I am very interesting in use this SDK to create, update, delete projects (using templates). I can see that there isn´t documentation about this.
Could you help me in this question?

Thank you so much for your help.

Regards

**Comment by jcantrill** [comment]
Creating a project is a matter of submitting a 'project request'.  Create a connection to your OpenShift cluster like: https://github.com/openshift/openshift-restclient-java#usage and then make a project request like: https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/NewProjectWizardModel.java#L56  The difference is jbosstools-openshift encapsulates the client in a connection class.  You can simply call client#create.

**Comment by fernanzambrano** [comment]
Thank you sou much. Now I can create projects with the defaults parameters and the delete them.

Could you tell me if the SDK could create projects using templates?
I need to create projects in the same way than the cli command

oc process -f small-project.yaml -v PROJECT_NAME=fzgprojectname,PROJECT_DISPLAYNAME=fzgDisplayname,PROJ
ECT_DESCRIPTION=fzg_description,PROJECT_ADMIN_USER=n034636 | oc create -f

where small-project.yaml is the next:

apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: small-project
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admins
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  userNames: []
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
- apiVersion: v1
  groupNames: []
  kind: ResourceQuota
  metadata:
    name: small.project
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      cpu: "2"
      memory: 2G
      pods: "20"
      replicationcontrollers: "20"
      resourcequotas: "20"
      services: "20"
  status: {}

- apiVersion: v1
  groupNames: []
  kind: LimitRange
  metadata:
    name: small-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        cpu: "2"
        memory: 1G
      min:
        cpu: 100m
        memory: 256M
      type: Pod
    - default:
        cpu: 100m
        memory: 256M
      max:
        cpu: "2"
        memory: 1G
      min:
        cpu: 100m
        memory: 256M
      type: Container
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER

**Comment by jcantrill** [comment]
@fernanzambrano I believe you have a 'chicken and egg' problem in that you can not associate other resources before the project exists.  Also, project creation is restricted by policy so in most cases you can only create a project via a 'project request'.  The API does support templates as well as processing and applying them using the IProjectTemplateCapability.  Here is an example of how we process and apply a template: https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java#L63

**Comment by fernanzambrano** [comment]
Thank you for the quick response.

I am having very big problems to undestand how it is works, maybe the creation of projects using templates it is not the best solution to implement (in my case).
This is whats I need to do:

1-Create a Project (OK, I can do it using the information that you posted in your first comment)
2-Then, change the Quota. My user could be select in a group of options (small, medium, big). These Quotas are previously charged in the OpenShift by the Administrator.
3-Make the same than in step 2 but, this time, for the Resource limits.

Could you show me the correct way using your API?

Thanks a lot.

**Comment by jcantrill** [comment]
@fernanzambrano I need to correct my previous response after getting additional info.  Projects can be created from a template but is restricted by default.  You can see what the default project template provides to use for a base by using the OS binaries:
```
oadm create-bootstrap-project-template  -o yaml
```
Quota and resource limits could be added via a template but neither the OS binaries nor the rest client currently provide an implementation.  You would need to either submit a PR to update this library or provide the JSON directly in a template according to: https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#v1-resourcequota and https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#v1-limitrange

**Comment by fernanzambrano** [comment]
Thank you so, so much for your help.
I am working in this way

		String json = "{\"kind\":\"ResourceQuota\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"small.project\",\"namespace\":\"fzg-project-name\",\"creationTimestamp\":null},\"spec\":{\"hard\":{\"cpu\":\"2\",\"memory\":\"2G\",\"pods\":\"25\",\"replicationcontrollers\":\"25\",\"resourcequotas\":\"25\",\"services\":\"25\"}},\"status\":{\"phase\":\"Active\"}}";
		IResourceQuota resourceQuota = client.getResourceFactory().create(json);
		client.create(resourceQuota);
		
		json = "{\"kind\":\"LimitRange\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"small-limits\",\"namespace\":\"fzg-project-name\",\"creationTimestamp\":null},\"spec\":{\"limits\":[{\"type\":\"Pod\",\"max\":{\"cpu\":\"5\",\"memory\":\"1G\"},\"min\":{\"cpu\":\"100m\",\"memory\":\"512M\"}},{\"type\":\"Container\",\"max\":{\"cpu\":\"2\",\"memory\":\"1G\"},\"min\":{\"cpu\":\"100m\",\"memory\":\"256M\"},\"default\":{\"cpu\":\"100m\",\"memory\":\"256M\"}}]}}";
		LimitRange = client.getResourceFactory().create(json);
		client.create(LimitRange);

And I can see the changes in my project.
Regards

**Comment by jcantrill** [comment]
@fernanzambrano some options that might making the json less painful is to either jboss DMR library, which is the backing impl to this client or jackson to serialize a Map.  Keeps you from having to do all the escaping.
